export const GET_ERRORS = "GET_ERRORS";
export const RECEIVE_USERS = "RECEIVE_USERS";
export const REQUEST_USERS = "REQUEST_USERS";
export const RECEIVE_GAMES = "RECEIVE_GAMES";
export const REQUEST_GAMES = "REQUEST_GAMES";