export const GET_ERRORS = "GET_ERRORS";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const RECEIVE_SERVICES = "RECEIVE_SERVICES";
export const REQUEST_SERVICES = "REQUEST_SERVICES";
export const RECEIVE_USERS = "RECEIVE_USERS";
export const REQUEST_USERS = "REQUEST_USERS";